# Site
repository: sproogen/resume-theme
favicon: images/icon.png

# Content configuration version
version: 2

# Personal info
name: Régis Santet
title: PhD Student
#email:
#website:

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username:
github_username: rsantet
stackoverflow_username: 11345387/flewer47
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username:
linkedin_username: r%C3%A9gis-santet-64a263143
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username:
# googleplus_username: +jekyll
orcid_username: 0000-0002-7576-5003

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/pic.jpg
about_content: | 
  I am a Post Doctoral researcher under the supervision of [Emeric Bourasseau](https://scholar.google.com/citations?user=M4Tc3AMAAAAJ&hl=fr) and [Luca Messina](https://scholar.google.com/citations?hl=fr&user=_q0x3tsAAAAJ) at [CEA Cadarache](https://cadarache.cea.fr/cad/Pages/Accueil.aspx). Before, I was a PhD student under the supervision of [Gabriel Stoltz](https://cermics-lab.enpc.fr/gabriel-stoltz/) and [Tony Lelièvre](https://cermics.enpc.fr/~lelievre/) at [CERMICS](https://cermics-lab.enpc.fr/) (École des Ponts) and [MATHERIALS](https://team.inria.fr/matherials/) (INRIA Paris).

  Mail: [r......@xxxx.fr](https://mailhide.io/e/4R6XjXCx)

content:
  #- title: Projects 
  #  layout: list 
  #  content:
  #    - layout: top-middle
  #      title: Super awesome project
  #      link: github.com/sproogen
  #      # link_text: Project Website
  #      additional_links:
  #        - title:  sproogen/modern-resume-theme
  #          icon: fab fa-github
  #          url: github.com/sproogen/modern-resume-theme
  #        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #        #   icon: fab fa-github
  #        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #      quote: >
  #        This is probably one of the greatest apps ever created, if you don't #agree you're probably wrong.
  #      description: | 
  #        I started this project as a way if learning <mark>React</mark> and it #has since grown into a fully fledged app. I have learned many skills #through this and been I'm very proud of having this in my portfolio. If #you don't have a project as awesome as this I would advise you make one.
  #
  - title: Publications
    layout: text
    content: | 
      - T. Lelièvre, R. Santet, G. Stoltz, **Improving sampling by modifying the effective diffusion**, *Journal of Computational Physics* (2025) [DOI](https://doi.org/10.1016/j.jcp.2025.114313) - [arXiv](https://arxiv.org/abs/2410.00525) - [HAL](https://inria.hal.science/hal-04721179) - [Code](https://github.com/rsantet/Improving_Sampling_By_Modifying_The_Effective_Diffusion)
      - T. Lelièvre, G. A. Pavliotis, G. Robin, R. Santet, G. Stoltz, **Optimizing the diffusion coefficient of overdamped Langevin dynamics**, *Mathematics of Computations* (2025) [DOI](https://doi.org/10.1090/mcom/4098) - [arXiv](https://arxiv.org/abs/2404.12087) - [HAL](https://hal.science/hal-04568317) - [Python](https://github.com/rsantet/Optimal_Overdamped_Langevin_Diffusion_Python)/[Julia](https://github.com/rsantet/Optimal_Overdamped_Langevin_Diffusion_Julia) Code
      - T. Lelièvre, R. Santet, G. Stoltz, **Unbiasing Hamiltonian Monte Carlo algorithms for a general Hamiltonian function**, *Foundations of Computational Mathematics* (2024) [DOI](https://doi.org/10.1007/s10208-024-09677-4) - [arXiv](https://arxiv.org/abs/2303.15918) - [HAL](https://hal.science/hal-04050146) - [Code](https://github.com/rsantet/RMHMC)

  - title: Presented courses and tutorials
    layout: text
    content: |
      - Performing sampling of physical systems at equilibrium, [Summer School on Sampling High-Dimensional Probability Measures with Applications in (Non)Equilibrium Molecular Dynamics and Statistics](https://www.cecam.org/workshop-details/summer-school-on-sampling-high-dimensional-probability-measures-with-applications-in-nonequilibrium-molecular-dynamics-and-statistics-1448) - Birmingham, July 2025 - [Notebook](https://github.com/shiva-darshan/CECAMSummerSchool2025/blob/main/notebooks/equilibrium_sampling.ipynb), [GitHub repository](https://github.com/shiva-darshan/CECAMSummerSchool2025)
      - Discretization of Langevin dynamics and its Metropolization, [Sampling high-dimensional probability measures: applications in (non)equilibrium molecular dynamics and statistics](https://www.ceremade.dauphine.fr/~iacob/SINEQ-SummerSchool) - Champs-sur-Marne, September 2023 - [Notebook](https://github.com/noeblassel/SINEQSummerSchool2023/blob/main/notebooks/langevin.ipynb), [GitHub repository](https://github.com/noeblassel/SINEQSummerSchool2023)
      - Presenting MCMC methods in the molecular dynamics framework, [CERMICS JSJC 2022](https://cermics-lab.enpc.fr/seminaires/young-researchers-seminar/jsjc/) - Provins, November 2022 - [Notebook](./files/CERMICS_JSJC_2022_Phy_Stat_Num.ipynb)

  - title: Conferences and workshops
    layout: text
    content: |
      - Optimizing the diffusion of overdamped Langein dynamics:
        - [4th Italian Meeting on Probability and Mathematical Statistics](https://probabilityrome2024.it/) - Rome, June 2024 - [Slides](./files/Italian_Meeting_Probability_Statistics_Rome_2024.pdf)
        - [Mostly Monte Carlo](https://bonstats.github.io/mostlymontecarlo/) - Paris, January 2024 - [Slides](./files/Mostly_Monte_Carlo_2024.pdf)
        - [GAMM 2023 - Section 26: Modeling, analysis and simulation of molecular systems](https://jahrestagung.gamm-ev.de/annual-meeting-2023/program/sections/), Dresden, May 2023 - [Slides](./files/GAMM2023_Optimizing_Diffusion_Overdamped_Langevin.pdf)
        - [Birmingham Workshop: (Non)equilibrium Molecular Dynamics: Algorithms, Analysis, and Applications](https://www.eventbrite.com/e/nonequilibrium-molecular-dynamics-algorithms-analysis-and-applications-tickets-619146833847?keep_tld=1) - Birmingham, May 2023 - [Slides](./files/BIRMINGHAM_2023_Slides.pdf)
        - [ANR SINEQ Meeting](https://sites.google.com/view/aleiac/anr-sineq?pli=1) - Paris, December 2022 - [Slides](./files/ANR_SINEQ_2022_Optimizing_diffusion_equilibrium_nonequilibrium_dynamics.pdf)
      - Computing free energy differences using non-equilibrium dynamics, [d² reading group](https://www.stats.ox.ac.uk/d2-reading-group) - Oxford, October 2023 - [Slides](./files/d2_reading_group_free_energy_computations_using_non_equilibriums_dynamics.pdf)
      - Computational Statistical Physics : a numerical microscope, [Labex Bézout PhD Day 2024](https://indico.math.cnrs.fr/event/11955/overview) - Champs-sur-Marne, May 2024 - [Slides](./files/Labex_Bezout.pdf)
      - Unbiasing Hamiltonian Monte Carlo algorithms for a general Hamiltonian function:
        - [MCM 2023](https://mcm2023.sciencesconf.org/) - Paris, June 2023 - [Slides](./files/MCM_2023_Unbiasing_HMC_For_General_Hamiltonian_Functions.pdf)
        - [MCQMC 2022](https://www.ricam.oeaw.ac.at/events/conferences/mcqmc2022/) - Linz, July 2022 - [Slides](./files/MCQMC_2022_Ensuring_Unbiased_Sampling_of_HMC_Schemes_for_Non_Separable_Hamiltonian_Systems.pdf)
        - [CECAM - Mixed-gen Season 2 – Session 7: Simulating non-equilibrium phenomena and rare events](https://www.cecam.org/workshop-details/1107)- Online, April 2022 - [Slides](./files/CECAM_2022_Mixed_Gen_Simulating_Noneq_Phenomena_Rare_Events_2022_Talk.pdf), [Talk](https://youtu.be/3iK5a0a-0TY?t=535)
        - [CERMICS - Young Researchers Seminar](https://cermics-lab.enpc.fr/seminaires/young-researchers-seminar/) - Champs-sur-Marne, March 2022 - [Slides](files/CERMICS_March_2022_PhD_Seminar.pdf)

  - title: Posters
    layout: text
    content: | 
      - Optimizing the diffusion of overdamped Langein dynamics, [Mascot-Num 2023](https://mascotnum2023.sciencesconf.org/) - Le Croisic, April 2023 - [Poster](./files/MASCOT_NUM_2023_Poster.pdf), [Blitz Slide](./files/MASCOT_NUM_2023_Blitz_Slide.pdf)
      - Unbiasing Hamiltonian Monte Carlo algorithms for a general Hamiltonian function, [CECAM - Numerical Techniques for Nonequilibrium Steady States](https://www.cecam.org/workshop-details/36) - Mainz, April 2022 - [Poster](./files/CECAM_2022_Numerical_Techniques_Noneq_Steady_States_Poster.pdf)

  - title: General scientific communication
    layout: text
    content: |
      - [Ma Thèse en 180 secondes](https://mt180.fr/): 3 minutes to introduce my subject for the whole world to see - Champs-sur-Marne, March 2023 - [Finale Paris-Est Sup 2023 - Video (in French)](https://www.youtube.com/watch?v=R4xknDnXapg) - [Written interview (in French)](https://ingenius.ecoledesponts.fr/articles/ma-these-en-180-secondes-rencontre-avec-regis-santet/)
      - [Ingenius Podcast on my PhD subject (in French)](https://ingenius.ecoledesponts.fr/articles/la-dynamique-moleculaire-un-microscope-numerique-pour-lindustrie/)
      - I transcribed in LaTeX some mathematics exercices (and answers) that I prepared during my studies (L2 or CPGE MP* level in France). Everything is in French (and there are definitely typos here and there). 
      Content: abstract algebra, differential calculus, matrix calculus, linear differential equations, euclidean spaces, normed vector spaces, functions of a real variable, integration, inner product spaces, probabilities, matrix reduction, series, power series, sequences and series of functions. [GitHub repository](https://github.com/rsantet/Exos_Maths_Spe)

      An ongoing project is also to transcribe in LaTeX the physics course I followed the same year (L2 or CPGE MP* level in France). Everything is in French (and there are definitely typos here and there, again).
      Content (for now): 
      - Mechanics: non-inertial reference frames, friction between two solids
      - Electromagnetism: electromagnetic field, electrostatics, magnetostatics, electric dipoles, Maxwell equations, electromagnetic energy, waves in a vacuum, dispersion and attenuation of waves
      - Thermodynamics: open systems, heat transfers   
      [GitHub repository](https://github.com/rsantet/Physique_Chimie_L2)

  - title: Teaching
    layout: text
    content: | 
      - Mathematics in Action: practical sessions on scientific programming (integral computations, ODEs integration). 25 students. **École Nationale des Ponts et Chaussées, September 2023**
      - Introduction to mathematical epidemiology (SIR/SIS/SIER models, control methods, demographic variations, R0 computation, local and asymptotic stability of endemic equilibrium). Supervising a group project (4 students). **École Nationale des Ponts et Chaussées, January - March 2022**
      - [PDE course](http://cermics.enpc.fr/~legoll/edpef.html): Sobolev spaces, elliptic PDEs (Poisson like PDEs with Dirichlet/Neumann/Robin boundary conditions on bounded spaces), Lax-Milgram theorem, Poincare inequalities, calculus of variations (energetic viewpoint). Application to linear elasticity and obstacle problems. 25 students. **École Nationale des Ponts et Chaussées, April - May 2022, March-June 2023, April - June 2024**
      - [Analysis course](https://educnet.enpc.fr/course/view.php?id=566): Measure theory and integration, Hilbert spaces, Lebesgue spaces, Fourier series, Distribution theory, Partial differential equations, Finite difference methods, Fourier transform. Flipped classroom, 25 student. **École Nationale des Ponts et Chaussées, September - December 2022**
      - Project about the use of a nonconstant diffusion coefficient to produce a proposal move for a Metropolis-like algorithm based on the integration of the overdamped Langevin dynamics. Introduction to Markov chains, Markov chain Monte Carlo algorithms, Finite Elements method, optimization tools. Supervising a group project (4 students). **École Nationale des Ponts et Chaussées, February - June 2023**

  - title: Distinction
    layout: text
    content: | 
      - [Pasquet's Prize](https://www.fondationdesponts.fr/prix-pasquet/) - Valedictorian of École Nationale des Ponts et Chaussées (2022)
      - Bourse d'Excellence via the Chaire Saint-Gobain - École des Ponts ParisTech

  - title: Experience 
    layout: text 
    content: |
        - Post Doctoral researcher @ [CEA Cadarache](https://cadarache.cea.fr/cad/Pages/Accueil.aspx), February 2025 - present, under the supervision of [Emeric Bourasseau](https://scholar.google.com/citations?user=M4Tc3AMAAAAJ&hl=fr) and [Luca Messina](https://scholar.google.com/citations?hl=fr&user=_q0x3tsAAAAJ). AI potentials for the mixed oxide nuclear fuel. Languages: Python, Bash; Softwares: ABINIT, VASP, LAMMPS, FitSNAP, Dakota.
        - Recognized student @ [Department of Statistics](https://www.stats.ox.ac.uk/) (Oxford University), Michaelmas term (September - December 2023), under the supervision of [George Deligiannidis](https://www.stats.ox.ac.uk/~deligian/). Computing free energy differences using diffusion models techniques. Relevant topics include Jarzynski-Crooks' equality, annealed importance sampling, diffusion models, Schrödinger Bridge. Languages: Python.
        - PhD student @ [CERMICS](https://cermics-lab.enpc.fr/) (École des Ponts) and [MATHERIALS](https://team.inria.fr/matherials/) (INRIA Paris), October 2021 - September 2024, under the supervision of [Tony Lelièvre](https://cermics.enpc.fr/~lelievre/) and [Gabriel Stoltz](https://cermics-lab.enpc.fr/gabriel-stoltz/).
        - Research Intern @ [Green Shield Technology](https://greenshield.fr/), April - August 2021, under the supervision of [Renaud Dessalles](https://dessalles.github.io/). Mathematical epidemiology applied to the spread of beetroots diseases. Relevant topics include mathematical epidemiology, scientific computing, simulation. Languages: Python.
        - Data Scientist & Customer Success officer @ [FieldBox.ai](https://www.fieldbox.ai/), January - July 2020. Machine Learning challenges and IT support to customers (both front-end and back-end). Relevant topics include machine learning, IT systems, front-end and back-end development. Languages: Python, Bash, JavaScript, Erlang.
        - Research Intern @ [CEA DAM/DIF](https://www-dam.cea.fr/), June - November 2019, under the supervision of [Jean-Bernard Maillet](https://scholar.google.fr/citations?user=KaL3RUIAAAAJ&hl=fr). Applying mathematics to molecular dynamics. Relevant topics include statistical physics, machine learning, scientific computing. Languages: C++, Python; Softwares: LAMMPS, PLUMED2.

  - title: Education 
    layout: text 
    content: |
        - **Sorbonne Université**, Master's Degree, 2020 - 2021. *Master de la Modélisation* (Master of Modelisation), specializing in the *Analyse Numérique et Équations aux Dérivées Partielles* (Numerical Analysis and Partial Differential Equations) branch. Relevant topics include functional analysis, stochastic processes, numerical analysis, hyperbolic equations, multiscale systems, elliptic equations, Lorentzian differential geometry. Languages: Python, Julia.
        - **École Nationale des Ponts et Chaussées**, Engineering Degree, 2017 - 2021. Specialization in the *Modélisation, Analyse, Simulation* (Modelisation, Analysis, Simulation) Master. Relevant topics include functional analysis, stochastic processes, Fourier analysis, numerical analysis, scientific computing, probabilities, statistics, optimal control, operational research, artificial intelligence, quantum mechanics, economics. Languages: C++, Python, Julia, Git, LaTeX.

  - title: (Past) Projects 
    layout: text 
    content: |
      - Implementation in Julia of the multivariate effective sample size (multiESS) estimator, July 2023. [Code](https://github.com/rsantet/multiESS).
      - Data reduction in the context of cartography, February - May 2019, ENPC project with Be-Bound. State of the art on data reduction for maps for a mobile app development. Languages: JavaScript, Python, Bash, Git. 
      - Stochastic dynamics of a population using the Wright-Fisher model, October - December 2018, ENPC project. Research on random walks, Brownian motion and continuous martingales. Application to an allele population subject to mutations and selections. Languages: Julia, Git. [Code](https://github.com/rsantet/MOPSIProject) - [Poster](files/Poster_MOPSI_Wright_Fisher.pdf)
      - Implementation of the arcade game "Paratroopers", October - December 2018, ENPC project. Implementation of the video game in the context of a course on good habits for programming. Languages: C++, Git. [Code](https://github.com/rsantet/ProjetTDLOG)
      - Rare event probability estimation using the Adaptative Multilevel Splitting algorithm, September 2018, ENPC project. Implementatino of the AMS algorithm and application to molecular dynamics. Languages: Python, Git. [Code](https://github.com/ClementLasuen/AMS)
      - Data reduction applied to pollutants transport, March - June 2018, ENPC project. Application of the SVD algorithm to model the evolution of a pollutant using the advection equation. Languages: Python, Git. [Code](https://github.com/BatyLeo/Projet)
      - Modeling defaults in a crystal, January - March 2018, ENPC project. Learning Hartree-Fock theory and the effect of a perturbation on Schrödinger's equation. Language: Python.
      - Entropy coding, January - June 2017, CPGE Project. Learning Shannon's information theory and implementation of two lossless compression algorithms. Language: Python.
      - Using quaternions in video games, January - June 2016, CPGE Project. Using quaternions and Bézier's curves instead of Euler angles to implement 3D rotations in video games. Langage: Python.

  - title: Community Involvement 
    layout: text 
    content: |
      - Helping pupils and students with their homeworks with [Mosaïc](https://mosaic-a-montreuil.fr/), 2023 - 2024.
      - PhD representative of the [MSTIC doctoral school](https://www.paris-est-sup.fr/ecoles-doctorales/ecole-doctorale-mathematiques-et-stic-mstic/l-ed-mstic/), 2023. Administrative meetings.
      - PhD representative of the [CERMICS laboratory](https://cermics-lab.enpc.fr/), 2022 - 2023. 3 days seminar organization, administrative meetings.
      - Member of the [Running Vincennes Association](https://www.running-vincennes.fr/), 2021 - 2024.
      - Member of a sustainable development association [Dévelop'Ponts](http://developponts.enpc.org/), 2018 - 2019. Sustainable development projects, distribution of veggie baskets to students and administratives, website update (that has now been completely remodelled). Langages: PHP, HTML, Git.
      - Member of the ENPC IT club [KIClubInfo](https://clubinfo.enpc.org/), 2018 - 2019. In charge of the club's finances. Organization of [LaTeX formations](https://clubinfo.enpc.org/formations.php) for ENPC students. Langages: LaTeX, Git.
      - Co-founder of the ENPC chess club, Pions & Chaussées, 2018 - 2019. Organization of chess tournaments, and introduction to the game to ENPC students. Co-founder of the [ENPC Lichess team](https://lichess.org/team/pions-et-chaussees).

# Footer
#footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
