# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Régis Santet
title: PhD Student
email: regis.santet@enpc.fr
#website:

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username:
github_username: rsantet
stackoverflow_username: 11345387/flewer47
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
linkedin_username: r%C3%A9gis-santet-64a263143
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/pic.png
about_content: | # this will include new lines to allow paragraphs
  I am a PhD student in computational statistical physics under the direction of [Gabriel Stoltz](https://cermics-lab.enpc.fr/gabriel-stoltz/) and [Tony Lelièvre](https://cermics.enpc.fr/~lelievre/) at [CERMICS](https://cermics-lab.enpc.fr/) and [MATHERIALS](https://team.inria.fr/matherials/) (INRIA).

content:
  #- title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: top-middle
  #      title: Super awesome project
  #      link: github.com/sproogen
  #      # link_text: Project Website
  #      additional_links:
  #        - title:  sproogen/modern-resume-theme
  #          icon: fab fa-github
  #          url: github.com/sproogen/modern-resume-theme
  #        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #        #   icon: fab fa-github
  #        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #      quote: >
  #        This is probably one of the greatest apps ever created, if you don't #agree you're probably wrong.
  #      description: | # this will include new lines to allow paragraphs
  #        I started this project as a way if learning <mark>React</mark> and it #has since grown into a fully fledged app. I have learned many skills #through this and been I'm very proud of having this in my portfolio. If #you don't have a project as awesome as this I would advise you make one.
#
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Green Shield Technology
        link: https://greenshield.fr/
        # link_text: 
        sub_title: Research Intern
        caption: April 2021 - August 2021
        #quote: >
        description: | # this will include new lines to allow paragraphs
            Mathematical epidemiology applied to the spread of beetroots diseases.

            Topics: mathematical epidemiology, scientific computing, simulation.

            Languages: Python
      - layout: left
        title: FieldBox.ai
        link: fieldbox.ai
        sub_title: Data Scientist & Customer Success officer
        caption: January 2020 - July 2020
        description: |
            Machine Learning challenges and IT support to customers (both front-end and back-end).

            Topics: machine learning, IT systems, front-end and back-end development.

            Languages: Python, Bash, JavaScript, Erlang.

      - layout: left
        title: CEA DAM/DIF
        link: 
        # link_text: 
        sub_title: Research Intern
        caption: June 2019 - November 2019
        #quote: >
        description: | # this will include new lines to allow paragraphs
            Applying mathematics to molecular dynamics.

            Topics: statistical physics, machine learning, scientific computing.

            Languages: C++, Python

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sorbonne Université
        caption: 2020-2021
        sub_title: Master Degree
        #quote: >
        description: | # this will include new lines to allow paragraphs
          **Master de la Modélisation** (Master of Modelisation), specializing in the **Analyse Numérique et Équations aux Dérivées Partielles** (Numerical Analysis and Partial Differential Equations) branch.

          Topics: functional analysis, stochastic processes, numerical analysis, hyperbolic equations, multiscale systems, elliptic equations, Lorentzian differential geometry.
          
      - layout: left
        title: École Nationale des Ponts et Chaussées
        caption: 2017 - 2021
        sub_title: Engineering Degree
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Specialization in the **Modélisation, Analyse, Simulation** (Modelisation, Analysis, Simulation) Master

          Topics: functional analysis, stochastic processes, Fourier analysis, numerical analysis, scientific computing, probabilities, statistics, optimal control, operational research, artificial intelligence, quantum mechanics, economics.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in mathematics, physics and computers, some of my other interests and hobbies are:
      - Sports (Running, Badminton)
      - Gaming (Metroidvanias)
      - [Chess](https://lichess.org/@/FlewerBoy)

# Footer
#footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
