# Site
repository: sproogen/resume-theme
favicon: images/icon.png

# Content configuration version
version: 2

# Personal info
name: Régis Santet
title: PhD Student
email: regis.santet@enpc.fr
#website:

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username:
github_username: rsantet
stackoverflow_username: 11345387/flewer47
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username:
linkedin_username: r%C3%A9gis-santet-64a263143
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username:
# googleplus_username: +jekyll
orcid_username: 0000-0002-7576-5003

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/pic.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a PhD student in computational statistical physics under the direction of [Gabriel Stoltz](https://cermics-lab.enpc.fr/gabriel-stoltz/) and [Tony Lelièvre](https://cermics.enpc.fr/~lelievre/) at [CERMICS](https://cermics-lab.enpc.fr/) (École des Ponts) and [MATHERIALS](https://team.inria.fr/matherials/) (INRIA Paris).
  Relevant topics include:
  - overdamped/underdamped Langevin dynamics
  - sampling of probability measures in high dimensions
  - Markov Chain Monte Carlo methods (Metropolis-Hastings, Hamiltonian Monte Carlo)
  - numerical analysis
  - non-equilibrium systems: perturbed dynamics with non gradient flows, linear response, transport coefficients
  - numerical integration (Julia)

  Other topics I am interested in:
  - machine Learning techniques
  - solving PDEs/SDEs
  - numerical tools for scientific programming

content:
  #- title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: top-middle
  #      title: Super awesome project
  #      link: github.com/sproogen
  #      # link_text: Project Website
  #      additional_links:
  #        - title:  sproogen/modern-resume-theme
  #          icon: fab fa-github
  #          url: github.com/sproogen/modern-resume-theme
  #        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #        #   icon: fab fa-github
  #        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #      quote: >
  #        This is probably one of the greatest apps ever created, if you don't #agree you're probably wrong.
  #      description: | # this will include new lines to allow paragraphs
  #        I started this project as a way if learning <mark>React</mark> and it #has since grown into a fully fledged app. I have learned many skills #through this and been I'm very proud of having this in my portfolio. If #you don't have a project as awesome as this I would advise you make one.
  #
  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - T. Lelièvre, R. Santet, G. Stoltz, *Unbiasing Hamiltonian Monte Carlo algorithms for a general Hamiltonian function*. (2023) [Preprint arXiv](https://arxiv.org/abs/2303.15918) - [Preprint HAL](https://hal.science/hal-04050146), [PDF](./files/Article_Unbiasing_HMC.pdf), [Code](https://github.com/rsantet/RMHMC)

  - title: Conferences
    layout: text
    content: | # this will include new lines to allow paragraphs
      - May 2023 - [GAMM 2023 - Section 26: Modeling, analysis and simulation of molecular systems](https://jahrestagung.gamm-ev.de/annual-meeting-2023/program/sections/). *Optimizing the diffusion of overdamped Langevin dynamics* ([Slides](./files/GAMM2023_Optimizing_Diffusion_Overdamped_Langevin.pdf))
      - May 2023 - [Birmingham Workshop: (Non)equilibrium Molecular Dynamics: Algorithms, Analysis, and Applications](https://www.eventbrite.com/e/nonequilibrium-molecular-dynamics-algorithms-analysis-and-applications-tickets-619146833847?keep_tld=1). *Optimizing the diffusion of overdamped Langevin dynamics* ([Slides](./files/BIRMINGHAM_2023_Slides.pdf))
      - April 2023 - [Mascot-Num 2023](https://mascotnum2023.sciencesconf.org/). *Optimizing the diffusion of overdamped Langevin dynamics* ([Poster](./files/MASCOT_NUM_2023_Poster.pdf), [Blitz Slide](./files/MASCOT_NUM_2023_Blitz_Slide.pdf))
      - March 2023 - [Ma Thèse en 180 secondes](https://mt180.fr/). 3 minutes to introduce my subject for the whole world to see. [Finale Paris-Est Sup 2023 - Video (in French)](https://www.youtube.com/watch?v=R4xknDnXapg)
      - December 2022 - [ANR SINEQ Meeting](https://sites.google.com/view/aleiac/anr-sineq?pli=1). *Optimizing the diffusion for equilibrium and nonequilibrium dynamics* ([Slides](./files/ANR_SINEQ_2022_Optimizing_diffusion_equilibrium_nonequilibrium_dynamics.pdf))
      - November 2022 - [CERMICS JSJC 2022](https://cermics-lab.enpc.fr/seminaires/young-researchers-seminar/jsjc/). *Presenting MCMC methods in the molecular dynamics framework* ([Notebook](./files/CERMICS_JSJC_2022_Phy_Stat_Num.ipynb))
      - July 2022 - [MCQMC 2022](https://www.ricam.oeaw.ac.at/events/conferences/mcqmc2022/). *Ensuring unbiased sampling of HMC schemes for non separable Hamiltonian systems* ([Slides](./files/MCQMC_2022_Ensuring_Unbiased_Sampling_of_HMC_Schemes_for_Non_Separable_Hamiltonian_Systems.pdf))
      - April 2022 - [CECAM - Mixed-gen Season 2 – Session 7: Simulating non-equilibrium phenomena and rare events](https://www.cecam.org/workshop-details/1107). *Genuinely unbiased Metropolis schemes for Langevin-like dynamics* ([Slides](./files/CECAM_2022_Mixed_Gen_Simulating_Noneq_Phenomena_Rare_Events_2022_Talk.pdf), [Talk](https://youtu.be/3iK5a0a-0TY?t=535))
      - April 2022 - [CECAM - Numerical Techniques for Nonequilibrium Steady States](https://www.cecam.org/workshop-details/36). *Unbiased sampling of HMC schemes for non separable Hamiltonian systems* ([Poster](./files/CECAM_2022_Numerical_Techniques_Noneq_Steady_States_Poster.pdf))
      - March 2022 - [CERMICS - Young Researchers Seminar](https://cermics-lab.enpc.fr/seminaires/young-researchers-seminar/). *Discretizing Langevin dynamics with multiplicative noise for sampling high-dimensional probability measures* ([Slides](files/CERMICS_March_2022_PhD_Seminar.pdf))

  - title: Teaching
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Introduction to mathematical epidemiology (SIS/SIS/SIER models, control methods, demographic variations, R0 computation, local and asymptotic stability of endemic equilibrium). Supervising a group project (4 students). **École Nationale des Ponts et Chaussées, January-March 2022**
      - [PDE course](http://cermics.enpc.fr/~legoll/edpef.html): Sobolev spaces, elliptic PDEs (Poisson like PDEs with Dirichlet/Neumann/Robin boundary conditions on bounded spaces), Lax-Milgram theorem, Poincare inequalities, calculus of variations (energetic viewpoint). Application to linear elasticity and obstacle problems. 25 students. **École Nationale des Ponts et Chaussées, April-May 2022 and March-June 2023**
      - [Analysis course](https://educnet.enpc.fr/course/view.php?id=566): Measure theory and integration, Hilbert spaces, Lebesgue spaces, Fourier series, Distribution theory, Partial differential equations, Finite difference methods, Fourier transform. Flipped classroom, 25 student. **École Nationale des Ponts et Chaussées, September-December 2022**
      - Project about the use of a nonconstant diffusion coefficient to produce a proposal move for a Metropolis-like algorithm based on the integration of the overdamped Langevin dynamics. Introduction to Markov chains, Markov chain Monte Carlo algorithms, Finite Elements method, optimization tools. Supervising a group project (4 students). **École Nationale des Ponts et Chaussées, February-June 2023**

  - title: Distinction
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [Pasquet's Prize](https://www.fondationdesponts.fr/prix-pasquet/) - Valedictorian of École Nationale des Ponts et Chaussées (2022)
      - Bourse d'Excellence via the Chaire Saint-Gobain - École des Ponts ParisTech

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Green Shield Technology
        link: https://greenshield.fr/
        link_text: greenshield.fr
        sub_title: Research Intern
        caption: April 2021 - August 2021
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Mathematical epidemiology applied to the spread of beetroots diseases.

          * Topics: mathematical epidemiology, scientific computing, simulation

          * Languages: Python

      - layout: left
        title: FieldBox.ai
        link: fieldbox.ai
        sub_title: Data Scientist & Customer Success officer
        caption: January 2020 - July 2020
        description: |
          Machine Learning challenges and IT support to customers (both front-end and back-end).

          * Topics: machine learning, IT systems, front-end and back-end development

          * Languages: Python, Bash, JavaScript, Erlang

      - layout: left
        title: CEA DAM/DIF
        link:
        # link_text:
        sub_title: Research Intern
        caption: June 2019 - November 2019
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Applying mathematics to molecular dynamics.

          * Topics: statistical physics, machine learning, scientific computing

          * Languages: C++, Python

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sorbonne Université
        caption: 2020-2021
        sub_title: Master Degree
        #quote: >
        description: | # this will include new lines to allow paragraphs
          **Master de la Modélisation** (Master of Modelisation), specializing in the **Analyse Numérique et Équations aux Dérivées Partielles** (Numerical Analysis and Partial Differential Equations) branch.

          * Topics: functional analysis, stochastic processes, numerical analysis, hyperbolic equations, multiscale systems, elliptic equations, Lorentzian differential geometry.

          * Languages: Python, Julia

      - layout: left
        title: École Nationale des Ponts et Chaussées
        caption: 2017 - 2021
        sub_title: Engineering Degree
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Specialization in the **Modélisation, Analyse, Simulation** (Modelisation, Analysis, Simulation) Master.

          * Topics: functional analysis, stochastic processes, Fourier analysis, numerical analysis, scientific computing, probabilities, statistics, optimal control, operational research, artificial intelligence, quantum mechanics, economics

          * Languages: C++, Python, Julia, Git, LaTeX

  - title: Past Projects [in French] # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Réduction de données dans le contexte de cartes géographiques
        caption: Février - Mai 2019
        sub_title: Projet ENPC avec Be-Bound
        #quote: >
        description: | # this will include new lines to allow paragraphs
          État de l'Art sur la compression de données de cartes géographiques pour la distribution d'une application mobile par Be-Bound.

          * Langages: JavaScript, Python, Bash, Git

      - layout: left
        title: Dynamique stochastique d'une population à l'aide du modèle de Wright-Fisher
        caption: Octobre - Décembre 2018
        sub_title: Projet ENPC
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Recherche sur les marches aléatoires, mouvements browniens et martingales continues. Application à l'évolution d'une population d'allèles avec des phénomènes de mutations et sélections.

          * Langages: Julia, Git

      - layout: left
        title: Implémentation du jeu d'arcade "Paratroopers"
        caption: Octobre - Décembre 2018
        sub_title: Projet ENPC
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Implémentation du jeu vidéo dans le cadre d'un cours sur les bonnes méthodes de programmation.

          * Langages: C++, Git

      - layout: left
        title: Estimation de probabilité dans le contexte d'évènements rares
        caption: Septembre 2018
        sub_title: Projet ENPC
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Implémentation de l'algorithme *Adaptative Multilevel Splitting* (AMS) pour estimer des probabilités rares. Application à la dynamique moléculaire.

          * Langages: Python, Git.

      - layout: left
        title: Réduction de modèles appliquée au transport d'un polluant
        caption: Mars - Juin 2018
        sub_title: Projet ENPC
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Application d'un algorithme de réduction (SVD) pour modéliser l'évolution d'un polluant grâce à l'équation d'advection.

          * Langages: Python, Git

      - layout: left
        title: Modélisation de défauts dans un cristal quantique
        caption: Janvier - Mars 2018
        sub_title: Projet ENPC
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Recherche sur la théorie d'Hartree-Fock et sur l'effet d'une perturbation dans l'équation de Schrödinger.

          * Langage: Python

      - layout: left
        title: Codage entropique
        caption: Janvier - Juin 2017
        sub_title: Projet CPGE
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Recherche sur la théorie de l'information de Shannon et implémentation de deux algorithmes de compressions sans perte.

          * Langage: Python

      - layout: left
        title: Utilisation des quaternions dans les jeux-vidéos
        caption: Janvier - Juin 2016
        sub_title: Projet CPGE
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Recherche sur les angles d'Euler, les quaternions et les courbes de Bézier pour les rotations 3D dans les jeux-vidéos.

          * Langage: Python

      - layout: left
        title: Fractales et Pavages
        caption: Mars - Mai 2015
        sub_title: Projet CPGE
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Recherche sur les pavages et les formes partitionnant le plan.

          * Langage: Python

  - title: Community Involvement # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ED MSTIC
        caption: 2023 - Present
        sub_title: PhD representative
        #quote: >
        description: | # this will include new lines to allow paragraphs
          PhD representative of the [MSTIC doctoral school](https://www.paris-est-sup.fr/ecoles-doctorales/ecole-doctorale-mathematiques-et-stic-mstic/l-ed-mstic/)

      - layout: left
        title: CERMICS
        caption: 2021 - Present
        sub_title: PhD representative
        #quote: >
        description: | # this will include new lines to allow paragraphs
          PhD representative of the [CERMICS laboratory](https://cermics-lab.enpc.fr/) (seminar organization, administrative meetings)

      - layout: left
        title: Running Vincennes Association
        caption: 2021 - Present
        sub_title: Member
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Active runner of the [running club of Vincennes](https://www.running-vincennes.fr/).

      - layout: left
        title: Dévelop'Ponts
        caption: 2018 - 2019
        sub_title: Member of a sustainable development association
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Sustainable development projects, distribution of veggie baskets to students and administratives, [website update (that is now being remodelled)](http://developponts.enpc.org/).

          * Langages: PHP, HTML, Git

      - layout: left
        title: KIClubInfo
        caption: 2018 - 2019
        sub_title: Treasurer of the IT club at ENPC.
        #quote: >
        description: | # this will include new lines to allow paragraphs
          In charge of the [club](https://clubinfo.enpc.org/)'s finances. Organization of [LaTeX formations](https://clubinfo.enpc.org/formations.html) for ENPC students.

          * Langages: LaTeX, Git

      - layout: left
        title: Pions & Chaussées
        caption: 2018 - 2019
        sub_title: Co-founder of the ENPC chess club
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Organization of chess tournaments, and introduction to the game to ENPC students. Co-founder of the [ENPC Lichess team](https://lichess.org/team/pions-et-chaussees).

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in mathematics, physics and computers, some of my other interests and hobbies are:
      - Sports (Running, Badminton, Tennis, Table Tennis)
      - Gaming (Metroidvanias, active member of the [GH community](https://www.scorehero.com/forum/profile.php?mode=viewprofile&u=507557))
      - [Chess](https://lichess.org/@/rsantboy)

# Footer
#footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
